#!/bin/sh

# PROVIDE: xray
# REQUIRE: DAEMON NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name="xray"
rcvar="${name}_enable"
command="/usr/sbin/${name}"
start_cmd="${name}_start"
stop_cmd="${name}_stop"
status_cmd="${name}_status"
pidfile="/var/run/${name}.pid"

location="/bin/xray/"

xray_start() {
    if pgrep ${name} > /dev/null; then
	echo "Already started, nothing to do"
    else
	echo "Starting..."
        nohup ${location}${name} -c ${location}config.json >>/var/run/${name}.output 2>&1 &
        echo $! >> /var/run/${name}.pid
        echo "Started."
    fi
}

xray_stop() {
	if pgrep ${name} > /dev/null; then
		echo "Stopping x-ray..."
		kill `cat /var/run/${name}.pid`
		rm -f /var/run/${name}.pid
		rm -f /var/run/${name}.output
		echo "x-ray stopped."
	else
		echo "Not running, nothing to do."
	fi
}

xray_status() {
    if pgrep ${name} > /dev/null; then
        echo "${name} is running\nStatus:"
        tail -n 14 /var/run/${name}.output
        return 0
    else
        echo "${name} is not running"
        return 1
    fi
}

load_rc_config $name
run_rc_command "$1"
